In [339]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import matplotlib.pyplot as plt

In [340]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

In [341]:
data = load_wine()

In [342]:
list(data.target_names)

['class_0', 'class_1', 'class_2']

In [343]:
data.data.shape, data.target.shape

((178, 13), (178,))

In [344]:
data = np.c_[data['data'], data['target']]

In [345]:
from sklearn import preprocessing


In [346]:
target = data[:, -1]

In [347]:
target

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2.])

In [348]:
data = data[:, :-1]

In [349]:
data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [350]:
# data = preprocessing.normalize(data)

In [351]:
data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [352]:
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.33, shuffle=True, random_state=0)

In [353]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((119, 13), (59, 13), (119,), (59,))

In [354]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(13,)),
    keras.layers.Dense(500, activation='relu'),
    keras.layers.Dense(500, activation='relu'),
    keras.layers.Dense(500, activation='relu'),
    keras.layers.Dense(3)
])

In [355]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])


In [356]:
hstr = model.fit(X_train, y_train, epochs=9, verbose=2)

Epoch 1/9
4/4 - 1s - loss: 78.8197 - accuracy: 0.3193 - 856ms/epoch - 214ms/step
Epoch 2/9
4/4 - 0s - loss: 43.4181 - accuracy: 0.3277 - 34ms/epoch - 9ms/step
Epoch 3/9
4/4 - 0s - loss: 32.6736 - accuracy: 0.3866 - 32ms/epoch - 8ms/step
Epoch 4/9
4/4 - 0s - loss: 11.3322 - accuracy: 0.3361 - 30ms/epoch - 8ms/step
Epoch 5/9
4/4 - 0s - loss: 10.1766 - accuracy: 0.3109 - 31ms/epoch - 8ms/step
Epoch 6/9
4/4 - 0s - loss: 9.2731 - accuracy: 0.3613 - 37ms/epoch - 9ms/step
Epoch 7/9
4/4 - 0s - loss: 7.7068 - accuracy: 0.3782 - 29ms/epoch - 7ms/step
Epoch 8/9
4/4 - 0s - loss: 4.1951 - accuracy: 0.4118 - 25ms/epoch - 6ms/step
Epoch 9/9
4/4 - 0s - loss: 4.8065 - accuracy: 0.5714 - 30ms/epoch - 8ms/step


In [357]:
model.predict(X_test)

2/2 [==============================] - 0s 4ms/step


array([[  5.8391047 ,  -9.678711  , -17.253592  ],
       [ -2.8817294 ,   0.42178416,  -5.866847  ],
       [ -1.6963617 ,  -0.28432527,  -5.4985223 ],
       [  6.7276125 , -10.879542  , -18.692112  ],
       [ -2.2829993 ,   0.40594655,  -4.785716  ],
       [ -3.9278572 ,   1.3760009 ,  -5.7705355 ],
       [  9.123471  , -13.569333  , -22.054132  ],
       [ -0.25219604,  -1.9740545 ,  -7.1900787 ],
       [  0.33866373,  -2.407971  ,  -7.391823  ],
       [ -0.14167616,  -1.7492996 ,  -6.7673683 ],
       [  3.7031858 ,  -6.7134023 , -12.572806  ],
       [ -1.1599628 ,  -0.6830674 ,  -5.4111805 ],
       [ 12.158159  , -16.650082  , -25.360138  ],
       [  1.9196563 ,  -4.580638  , -10.212432  ],
       [  1.7240145 ,  -4.9249306 , -11.245006  ],
       [ -3.5156462 ,   2.0441258 ,  -3.2847044 ],
       [  7.3134346 , -11.736943  , -20.420258  ],
       [ 15.813713  , -20.390728  , -29.908165  ],
       [ -2.1129649 ,   0.05378819,  -5.61107   ],
       [ 10.692964  , -14.61899

In [358]:
probability_model = tf.keras.Sequential([model, 
                                         tf.keras.layers.Softmax()])
predictions = probability_model.predict(X_test)

2/2 [==============================] - 0s 5ms/step


In [359]:
print(predictions[-1],
      np.argmax(predictions[-1]),
      X_test[-1],
      sep='\n')

[0.11735232 0.8785784  0.00406922]
1
[1.386e+01 1.510e+00 2.670e+00 2.500e+01 8.600e+01 2.950e+00 2.860e+00
 2.100e-01 1.870e+00 3.380e+00 1.360e+00 3.160e+00 4.100e+02]
